### ISSUE TITLE
Source code not available yet, and some ideas

### ISSUE THREAD

**Issue by mslavescu** [KIT-MRT/coco#1]
I've been looking for this for a few months, to use it in http://OSSDC.org Simulator (see some examples here https://www.youtube.com/watch?v=dqnjHqwP68Y&list=PLUop7b1Q1uZmH8c9Ok-_cXpiHMrKng2t5), on mono or stereo videos, also from unknown cameras, like Youtube dashcam videos or PS3/PS4 games recordings.

Your approach looks very promising, and I would love to be able to test it on live video from games or mid/full size SDC.

Could you please post the code used to produce the results from the article?

Have you looked into detection algorithms like SSD, to automatically find relevant landmarks?

Or using something like this?
https://chatbotslife.com/ideas-for-landmark-detection-on-car-parts-wheels-windows-license-plates-etc-212df81c0a82

**Comment by ShreyasSkandan** [comment]
Following up to see if there are plans to make this available?

**Comment by PNeigel** [comment]
Bump. Any plans to make it available (again?) ?

**Comment by FruityWelsh** [comment]
Bump. Also interested in source code.

**Comment by CharlieA0** [comment]
Bump. Interested in source code.

**Comment by nikolausmayer** [comment]
Bump. Please provide the source code, as stated in the published paper :pray:

**Comment by cagcoach** [comment]
@eikreh Bump. I would also be very interested in this code...
